# Generated by Django 4.2.5 on 2024-02-14 05:46

import authentification.manager
import authentification.validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_login_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "USERID",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                (
                    "USERNAME",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[authentification.validation.validate_no_dot],
                    ),
                ),
                ("PASSWORD", models.CharField(max_length=150)),
                (
                    "USER_TYPE",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GU", "General-User"),
                            ("SU", "Superuser-User"),
                            ("AU", "Admin-User"),
                            ("UU", "Athorizised-User"),
                        ],
                        default="GU",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "EMAIL",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="email address"
                    ),
                ),
                ("MOBILE_NO", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "SU_APRO_STAT",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVED", "User-APPROVED"),
                            ("REJECTED", "User-REJECTED"),
                            ("BLOCKED", "User-BLOCKED"),
                            ("DELETE", "User-DELETE"),
                            ("INPROGRESS", "INPROGRESS"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "AU_APRO_STAT",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVED", "User-APPROVED"),
                            ("REJECTED", "User-REJECTED"),
                            ("BLOCKED", "User-BLOCKED"),
                            ("DELETE", "User-DELETE"),
                            ("INPROGRESS", "INPROGRESS"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("APRO_DATE", models.DateTimeField(null=True)),
                (
                    "SU_APRO_REM",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "AU_APRO_REM",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Q1_ID", models.IntegerField(null=True)),
                ("Q2_ID", models.IntegerField(null=True)),
                ("Q1_AN", models.CharField(max_length=20, null=True)),
                ("Q2_AN", models.CharField(max_length=20, null=True)),
                ("THEME_OPT", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "CREATION_DATE",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "Login_Main_Data",
            },
            managers=[
                ("objects", authentification.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_mail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "customer_mobile_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("catagory", models.CharField(blank=True, max_length=100, null=True)),
                ("comment", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="THEME_MODULE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "USERID_THEME_OPT",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("THEME_TYPE", models.CharField(max_length=50, unique=True)),
                ("MODEL_1", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_2", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_3", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_4", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_5", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_6", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_7", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_8", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_9", models.CharField(blank=True, max_length=50, null=True)),
                ("MODEL_10", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "THEME_MODULE",
            },
        ),
        migrations.CreateModel(
            name="Users_login_Details_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("USER_F_NAME", models.CharField(max_length=20, null=True)),
                ("USER_M_NAME", models.CharField(blank=True, max_length=20, null=True)),
                ("USER_L_NAME", models.CharField(max_length=20, null=True)),
                ("GENDER", models.CharField(blank=True, max_length=20, null=True)),
                ("DOB", models.DateField(null=True)),
                ("ORGANIZATION", models.CharField(max_length=100, null=True)),
                ("DESIGNATION", models.CharField(max_length=50, null=True)),
                ("ADDRESS_1", models.CharField(blank=True, max_length=100, null=True)),
                ("ADDRESS_2", models.CharField(blank=True, max_length=100, null=True)),
                ("CITY", models.CharField(max_length=50, null=True)),
                ("STATE", models.CharField(max_length=50, null=True)),
                ("COUNTRY", models.CharField(max_length=50, null=True)),
                ("PIN_CODE", models.CharField(blank=True, max_length=6, null=True)),
                ("UU_REM", models.CharField(blank=True, max_length=200, null=True)),
                ("LAN_LINE", models.CharField(blank=True, max_length=15, null=True)),
                ("ALT_EMAIL", models.EmailField(blank=True, max_length=100, null=True)),
                ("OFF_LOCA", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "USERID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logindata",
                        to=settings.AUTH_USER_MODEL,
                        to_field="USERID",
                    ),
                ),
            ],
            options={
                "db_table": "Profile_Main_Data",
            },
        ),
        migrations.CreateModel(
            name="password_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forget_password_token",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "USERID",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="USERID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MODUL_VIEW_PERMISSION",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AU_ID", models.CharField(max_length=6)),
                ("MODEL_1", models.BooleanField(blank=True, null=True)),
                ("MODEL_2", models.BooleanField(blank=True, null=True)),
                ("MODEL_3", models.BooleanField(blank=True, null=True)),
                ("MODEL_4", models.BooleanField(blank=True, null=True)),
                ("MODEL_5", models.BooleanField(blank=True, null=True)),
                ("MODEL_6", models.BooleanField(blank=True, null=True)),
                ("MODEL_7", models.BooleanField(blank=True, null=True)),
                ("MODEL_8", models.BooleanField(blank=True, null=True)),
                ("MODEL_9", models.BooleanField(blank=True, null=True)),
                ("MODEL_10", models.BooleanField(blank=True, null=True)),
                (
                    "USERID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="USERID",
                    ),
                ),
                (
                    "USERID_THEME_OPT",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentification.theme_module",
                        to_field="USERID_THEME_OPT",
                    ),
                ),
            ],
            options={
                "db_table": "MODUL_VIEW_PERMISSION",
            },
        ),
    ]
