# Generated by Django 4.2.5 on 2024-02-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarsBandInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BAND_NAME", models.CharField(max_length=30)),
                ("BAND_S_SPEC", models.FloatField()),
                ("BAND_E_SPEC", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MarsBoundsCoordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("COOD_NO", models.IntegerField()),
                ("COOD_XX", models.FloatField()),
                ("COOD_YY", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MarsMainTableData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DATACODE", models.CharField(max_length=10, unique=True)),
                ("DATANAME", models.CharField(max_length=100)),
                ("COMP_NA", models.CharField(max_length=50)),
                ("SATT_NA", models.CharField(max_length=50)),
                ("CL_REF", models.CharField(max_length=50)),
                ("CL_ORDNA", models.CharField(max_length=50)),
                ("CL_PROJNA", models.CharField(max_length=100)),
                ("CL_PURPOSE", models.CharField(max_length=100)),
                ("CL_ADDRESS1", models.CharField(max_length=150)),
                ("CL_ADDRESS2", models.CharField(max_length=150)),
                ("SEN_NAME", models.CharField(max_length=20)),
                ("IMG_DATYPE", models.CharField(max_length=30)),
                ("IMG_DAPROC", models.CharField(max_length=20)),
                ("IMG_DATE", models.CharField(max_length=10)),
                ("IMG_DT_RNG", models.CharField(max_length=21)),
                ("DLOCA_CY", models.CharField(max_length=100)),
                ("DLOCA_ST", models.CharField(max_length=100)),
                ("DLOCA_DT", models.CharField(max_length=100)),
                ("DLOCA_LOCA", models.CharField(max_length=100)),
                ("DAREA", models.FloatField()),
                ("DSIZE", models.CharField(max_length=10)),
                ("DQLNAME", models.CharField(max_length=100)),
                ("DFORMAT", models.CharField(max_length=20)),
                ("DCLOUD", models.FloatField()),
                ("DSNOW", models.FloatField()),
                ("D_AQ_BITS", models.IntegerField()),
                ("D_PR_BITS", models.IntegerField()),
                ("DPRJ_TABLE", models.CharField(max_length=20)),
                ("DPRJ_NAME", models.CharField(max_length=6)),
                ("D_NROWS", models.IntegerField()),
                ("D_NCOLS", models.IntegerField()),
                ("D_NBANDS", models.IntegerField()),
                ("D_NTILES", models.IntegerField()),
                ("D_TYPE", models.CharField(max_length=20)),
                ("D_NBITS", models.IntegerField()),
                ("D_SIGN", models.CharField(max_length=10)),
                ("D_IN_ANGL", models.FloatField()),
                ("D_GSD_AXT", models.FloatField()),
                ("D_GSD_ALT", models.FloatField()),
                ("D_PIXELX", models.FloatField()),
                ("D_PIXELY", models.FloatField()),
                ("AL_DA_PATH", models.CharField(max_length=150)),
                ("AL_SH_PATH", models.CharField(max_length=150)),
                ("AL_QL_PATH", models.CharField(max_length=150)),
                ("XML_FILE", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name="marsmaintabledata",
            constraint=models.UniqueConstraint(
                fields=("DATACODE",), name="unique_datacode"
            ),
        ),
        migrations.AddField(
            model_name="marsboundscoordinates",
            name="DATACODE",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marsboundscoordinates",
                to="archival.marsmaintabledata",
                to_field="DATACODE",
            ),
        ),
        migrations.AddField(
            model_name="marsbandinformation",
            name="DATACODE",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marsbandinformation",
                to="archival.marsmaintabledata",
                to_field="DATACODE",
            ),
        ),
    ]
